# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT

description: PMW3610 Profile Switching behavior

compatible: "zmk,behavior-pmw3610-profile"

include: zero_param.yaml

properties:
  profile-type:
    type: string
    required: true
    enum:
      - "precision"
      - "speed"
